### ISSUE TITLE
Tiles not found

### ISSUE THREAD

**Issue by pierrebonbon** [infostreams/mbtiles-php#19]
I've been trying to load tiles from a .mbtiles file using mbtiles-php without much success. 

I followed the instructions and installed a foo.mbtiles file on the same folder as .htaccess and tileserver.php. I have GD and PDO enabled on my server. Here's the code:

> $(window).load(function() {
> var map = L.map('map').setView([74.2343, -54.43534], 14);
> L.tileLayer('./tiles/foo.mbtiles/{z}/{x}/{y}.png', {
> maxZoom: 19
> }).addTo(map);
> });

I'm getting several of these on my console:

> Failed to load resource: the server responded with a status of 404 (Not Found)
> http://43.000.00.0/tiles/foo.mbtiles/13/3888/3139.png

**Comment by pierrebonbon** [comment]
Of course **L.mapbox.map** does not accept mbtiles, so I changed my code to to accomodate **l.tileLayer**. Here's my new code:

>  $(window).load(function() {
>  var map = L.map('map').setView([74.2343, -54.43534], 14);
>  L.tileLayer('./tiles/foo.mbtiles/{z}/{x}/{y}.png', {    
>  maxZoom: 19
>  }).addTo(map);
>  });

I'm now getting several of these on my console:

> Failed to load resource: the server responded with a status of 404 (Not Found)
> http://43.000.00.0/tiles/foo.mbtiles/13/3888/3139.png

**Comment by infostreams** [comment]
I think the ".mbtiles" should not be in the URL.... Also, you should load this via the .tilejson path as indicated in the example. The TileJSON file contains important information about the map and is needed to properly initialize the map viewer. It is a "virtual" file, generated by the tilemap server, so you won't find it in your directory.

As a test, can you see if you can access

http://43.000.00.0/tiles/foo/13/3888/3139.png ?

**Comment by pierrebonbon** [comment]
Well, I had .htaccess usage disabled on my server! After enabling it, I'm getting blank (grey) tiles:

![screen shot 11-19-15 at 12 07 pm](https://cloud.githubusercontent.com/assets/11869768/11270478/537a862e-8eb7-11e5-8163-b0e7b7a4f7fe.PNG) 

Changing "foo.mbtiles" to "foo.tilejson" gives me a 404 not found

**Comment by infostreams** [comment]
Ah! You're getting a valid PNG of the correct dimensions, you mean. Try this:

http://46.101.76.4/tiles/

And then click on http://46.101.76.4/tiles/foo/2/1/1.png for example. I think your tileserver is working :-)

**Comment by pierrebonbon** [comment]
It is woring, that's awesome!!!

Now, what I don't get is how to do that on the script side. Any hints appreciated! :-)

**Comment by infostreams** [comment]
Just try to copy-paste the example, and then do something like

```
  L.mapbox.map('map', 'http://46.101.76.4/tiles/foo.tilejson');
```

But since this is not an issue with the tileserver itself, I'm closing this...

**Comment by pierrebonbon** [comment]
Thanks again. The following code seems to work fine with *Leaflet*:

    $(window).load(function() {
    var map = L.map('map').setView([74.2343, -54.43534], 14);
    L.tileLayer('./tiles/foo/{z}/{x}/{y}.png', {
    maxZoom: 18
    }).addTo(map);
    });

**Comment by infostreams** [comment]
Cool, thanks!
